services:
    redis:
        image: redis:7-alpine
        networks:
            - app-network
        volumes:
            - redis_data:/data
        ports:
            - '${REDIS_PORT:-6379}:6379'
        command: redis-server --appendonly yes

    postgres:
        image: postgres:18.4-alpine
        container_name: stedi-postgres
        volumes:
            - ./docker/postgres:/docker-entrypoint-initdb.d:ro
            - postgres_data:/var/lib/postgresql
        ports:
            - '${POSTGRES_PORT:-5432}:5432'
        environment:
            - POSTGRES_USER=${POSTGRES_USER:-postgres}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-stedi}
            - POSTGRES_DB=${POSTGRES_DB:-stedi}
        networks:
            - app-network

    mailpit:
        image: axllent/mailpit:latest
        container_name: stedi-mailpit
        ports:
            - '${MAILPIT_SMTP_PORT:-1025}:1025'
            - '${MAILPIT_WEBUI_PORT:-8025}:8025'
        networks:
            - app-network

    soketi:
        image: quay.io/soketi/soketi:1.6.1-16-debian
        networks:
            - app-network
        ports:
            - '${SOKETI_PORT:-6001}:6001'
        environment:
            SOKETI_DEBUG: '1'
            SOKETI_HOST: '0.0.0.0'
            SOKETI_PORT: '6001'
            SOKETI_MODE: 'full'
            # Drivers
            SOKETI_APP_MANAGER_DRIVER: 'postgres'
            SOKETI_QUEUE_DRIVER: 'redis'
            SOKETI_CACHE_DRIVER: 'redis'
            # CORS
            SOKETI_CORS_ALLOWED_ORIGINS: '*'
            SOKETI_CORS_ALLOWED_HEADERS: 'Origin,Content-Type,X-Auth-Token,X-Requested-With,Accept,Authorization,Cache-Control,X-XSRF-TOKEN,X-Socket-Id'
            # Redis
            SOKETI_DB_REDIS_HOST: 'redis'
            SOKETI_DB_REDIS_PORT: '6379'
            SOKETI_DB_REDIS_DB: '0'
            # PostgreSQL
            SOKETI_DB_POSTGRES_HOST: 'postgres'
            SOKETI_DB_POSTGRES_PORT: '5432'
            SOKETI_DB_POSTGRES_USER: 'postgres'
            SOKETI_DB_POSTGRES_PASSWORD: 'stedi'
            SOKETI_DB_POSTGRES_DATABASE: 'stedi'
            # Limits
            SOKETI_EVENT_LIMITS_MAX_CHANNELS_AT_ONCE: '1000'
            SOKETI_EVENT_LIMITS_MAX_NAME_LENGTH: '200'
            SOKETI_EVENT_LIMITS_MAX_PAYLOAD_IN_KB: '100'
            SOKETI_EVENT_LIMITS_MAX_BATCH_SIZE: '10'
            # Metrics
            SOKETI_METRICS_ENABLED: 'true'
            SOKETI_METRICS_DRIVER: 'prometheus'
            SOKETI_METRICS_HOST: '0.0.0.0'
            SOKETI_METRICS_SERVER_PORT: '9601'
            # Presence
            SOKETI_PRESENCE_MAX_MEMBERS_PER_CHANNEL: '1000'
            SOKETI_PRESENCE_MAX_MEMBER_SIZE_IN_KB: '2'
        depends_on:
            - postgres
            - redis

volumes:
    redis_data:
    postgres_data:

networks:
    app-network:
        driver: bridge
